# Generated by Django 3.2 on 2021-04-28 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='Código do título')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descriçã do título')),
            ],
        ),
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('titulo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cotacoes.titulo')),
                ('intervalo', models.PositiveIntegerField(default=15, verbose_name='Intervalo definido para coleta dos dados')),
                ('limite_superior', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Limite superior para venda')),
                ('limite_inferior', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Limite inferior para compra')),
            ],
        ),
        migrations.CreateModel(
            name='Monitoramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor do título')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp da coleta')),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotacoes.titulo')),
            ],
        ),
    ]
