# Generated by Django 3.2 on 2021-04-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracao',
            name='intervalo',
        ),
        migrations.AlterField(
            model_name='titulo',
            name='descricao',
            field=models.CharField(max_length=100, verbose_name='Descrição do título'),
        ),
    ]
