# Generated by Django 3.2 on 2021-05-01 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0002_auto_20210428_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalo_consulta', models.PositiveIntegerField(default=15, verbose_name='Intervalo definido para coleta dos dados')),
            ],
        ),
        migrations.RenameModel(
            old_name='Configuracao',
            new_name='ConfiguracaoTitulo',
        ),
    ]
