# Generated by Django 3.2 on 2021-05-03 04:21

import cotacoes.enums
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_enum_choices.choice_builders
import django_enum_choices.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0016_auto_20210503_0121'),
        ('cotacoes', '0003_auto_20210430_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaotitulo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracaotitulo',
            name='intervalo',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('15 min', '15 min'), ('30 mins', '30 mins'), ('45 mins', '45 mins'), ('1 hora', '1 hora')], default=cotacoes.enums.Intervalo['quinze_minutos'], enum_class=cotacoes.enums.Intervalo, max_length=7),
        ),
        migrations.AddField(
            model_name='configuracaotitulo',
            name='status',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default=cotacoes.enums.Status['ativo'], enum_class=cotacoes.enums.Status, max_length=7),
        ),
        migrations.AddField(
            model_name='configuracaotitulo',
            name='tarefa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask'),
        ),
    ]
