# Generated by Django 3.2 on 2021-05-04 23:57

import cotacoes.enums
from django.db import migrations, models
import django_enum_choices.choice_builders
import django_enum_choices.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0006_titulo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulo',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='titulo',
            name='status',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default=cotacoes.enums.Status['ativo'], enum_class=cotacoes.enums.Status, max_length=7),
        ),
    ]
