# Generated by Django 3.2 on 2021-05-05 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0007_auto_20210504_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaotitulo',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
