# Generated by Django 3.2 on 2021-05-12 05:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0008_configuracaotitulo_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaotitulo',
            name='limite_inferior',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Limite inferior para compra (R$)'),
        ),
        migrations.AlterField(
            model_name='configuracaotitulo',
            name='limite_superior',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Limite superior para venda (R$)'),
        ),
        migrations.AlterField(
            model_name='monitoramento',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Horário da coleta'),
        ),
        migrations.AlterField(
            model_name='monitoramento',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do título'),
        ),
        migrations.AlterField(
            model_name='monitoramento',
            name='variacao',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, verbose_name='Variação (%)'),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='codigo',
            field=models.CharField(max_length=10, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='descricao',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
    ]
